services:
  imposter:
    image: docker.io/outofcoffee/imposter-all:3.40.0
    container_name: imposter
    volumes:
      - ./config:/opt/imposter/config
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - IMPOSTER_JS_PLUGIN=js-graal
